"""Amtliche Finanzaemter-Liste (alle Bundeslaender) — kanonische Quelle fuer die
Stammdaten-Auswahl (PRD §3.2, dependent Bundesland -> Finanzamt).

Quelle: BZSt GemFA-Export (kontist/finanzamt, GemFA_Export_20250423), 601 Finanzaemter.
Gruppierung nach Bundesland ueber den amtlichen 4-stelligen BUFA-Nummernkreis
(Bundesfinanzamtsnummer). buFaNr ist bundesweit eindeutig -> Select-Value.
Generiert; nicht von Hand editieren.
"""
from __future__ import annotations

# 16 Bundeslaender (alphabetisch).
BUNDESLAENDER: list[str] = [
    'Baden-Württemberg',
    'Bayern',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thüringen',
]

# Bundesland -> Finanzaemter [{"bufa": <4-stellig>, "name": <amtlicher Name>}], nach Name sortiert.
FINANZAEMTER_BY_BUNDESLAND: dict[str, list[dict[str, str]]] = {
    'Baden-Württemberg': [
        {"bufa": '2850', "name": 'Aalen'},
        {"bufa": '2851', "name": 'Backnang'},
        {"bufa": '2889', "name": 'Bad Urach'},
        {"bufa": '2833', "name": 'Baden-Baden'},
        {"bufa": '2836', "name": 'Baden-Baden Außenstelle Bühl'},
        {"bufa": '2853', "name": 'Balingen'},
        {"bufa": '2854', "name": 'Biberach'},
        {"bufa": '2879', "name": 'Biberach Außenstelle Riedlingen'},
        {"bufa": '2855', "name": 'Bietigheim-Bissingen'},
        {"bufa": '2830', "name": 'Bruchsal'},
        {"bufa": '2856', "name": 'Böblingen'},
        {"bufa": '2845', "name": 'Calw'},
        {"bufa": '2858', "name": 'Ehingen'},
        {"bufa": '2805', "name": 'Emmendingen'},
        {"bufa": '2859', "name": 'Esslingen'},
        {"bufa": '2831', "name": 'Ettlingen'},
        {"bufa": '2807', "name": 'Freiburg-Land'},
        {"bufa": '2813', "name": 'Freiburg-Land Außenstelle Titisee-Neustadt'},
        {"bufa": '2806', "name": 'Freiburg-Stadt'},
        {"bufa": '2842', "name": 'Freudenstadt'},
        {"bufa": '2861', "name": 'Friedrichshafen'},
        {"bufa": '2863', "name": 'Göppingen'},
        {"bufa": '2862', "name": 'Göppingen Außenstelle Geislingen'},
        {"bufa": '2832', "name": 'Heidelberg'},
        {"bufa": '2864', "name": 'Heidenheim'},
        {"bufa": '2865', "name": 'Heilbronn'},
        {"bufa": '2834', "name": 'Karlsruhe-Durlach'},
        {"bufa": '2835', "name": 'Karlsruhe-Stadt'},
        {"bufa": '2809', "name": 'Konstanz'},
        {"bufa": '2810', "name": 'Lahr'},
        {"bufa": '2870', "name": 'Leonberg'},
        {"bufa": '2871', "name": 'Ludwigsburg'},
        {"bufa": '2811', "name": 'Lörrach'},
        {"bufa": '2837', "name": 'Mannheim-Neckarstadt'},
        {"bufa": '2838', "name": 'Mannheim-Stadt'},
        {"bufa": '2840', "name": 'Mosbach'},
        {"bufa": '2846', "name": 'Mosbach Außenstelle Walldürn'},
        {"bufa": '2848', "name": 'Mühlacker'},
        {"bufa": '2812', "name": 'Müllheim'},
        {"bufa": '2874', "name": 'Nürtingen'},
        {"bufa": '2869', "name": 'Nürtingen Außenstelle Kirchheim'},
        {"bufa": '2801', "name": 'Offenburg -01- (vormals ASt Achern)'},
        {"bufa": '2814', "name": 'Offenburg -14-'},
        {"bufa": '2808', "name": 'Offenburg Außenstelle Kehl'},
        {"bufa": '2823', "name": 'Offenburg Außenstelle Wolfach'},
        {"bufa": '2841', "name": 'Pforzheim'},
        {"bufa": '2849', "name": 'Pforzheim Außenstelle Neuenbürg'},
        {"bufa": '2839', "name": 'Rastatt'},
        {"bufa": '2877', "name": 'Ravensburg'},
        {"bufa": '2878', "name": 'Reutlingen'},
        {"bufa": '2819', "name": 'Rottweil'},
        {"bufa": '2815', "name": 'Rottweil Außenstelle Oberndorf'},
        {"bufa": '2882', "name": 'Schorndorf'},
        {"bufa": '2843', "name": 'Schwetzingen'},
        {"bufa": '2883', "name": 'Schwäbisch Gmünd'},
        {"bufa": '2884', "name": 'Schwäbisch Hall'},
        {"bufa": '2857', "name": 'Schwäbisch Hall Außenstelle Crailsheim'},
        {"bufa": '2885', "name": 'Sigmaringen'},
        {"bufa": '2881', "name": 'Sigmaringen Außenstelle Bad Saulgau'},
        {"bufa": '2818', "name": 'Singen'},
        {"bufa": '2844', "name": 'Sinsheim'},
        {"bufa": '2893', "name": 'Stuttgart I'},
        {"bufa": '2895', "name": 'Stuttgart II'},
        {"bufa": '2897', "name": 'Stuttgart III'},
        {"bufa": '2892', "name": 'Stuttgart IV'},
        {"bufa": '2896', "name": 'Stuttgart Zentrales Konzernprüfungsamt'},
        {"bufa": '2899', "name": 'Stuttgart-Körpersch.'},
        {"bufa": '2880', "name": 'Tauberbischofsheim'},
        {"bufa": '2852', "name": 'Tauberbischofsheim Außenstelle Bad Mergentheim'},
        {"bufa": '2821', "name": 'Tuttlingen'},
        {"bufa": '2886', "name": 'Tübingen'},
        {"bufa": '2888', "name": 'Ulm'},
        {"bufa": '2822', "name": 'Villingen-Schwenningen'},
        {"bufa": '2804', "name": 'Villingen-Schwenningen Außenstelle Donaueschingen'},
        {"bufa": '2890', "name": 'Waiblingen'},
        {"bufa": '2820', "name": 'Waldshut-Tiengen'},
        {"bufa": '2816', "name": 'Waldshut-Tiengen Außenstelle Bad Säckingen'},
        {"bufa": '2891', "name": 'Wangen'},
        {"bufa": '2847', "name": 'Weinheim'},
        {"bufa": '2876', "name": 'Öhringen'},
        {"bufa": '2887', "name": 'Überlingen (Bodensee)'},
    ],
    'Bayern': [
        {"bufa": '9201', "name": 'Amberg'},
        {"bufa": '9203', "name": 'Ansbach mit Außenstellen'},
        {"bufa": '9204', "name": 'Aschaffenburg'},
        {"bufa": '9102', "name": 'Augsburg-Land'},
        {"bufa": '9103', "name": 'Augsburg-Stadt'},
        {"bufa": '9101', "name": 'Augsburg-Stadt Arbeitnehmerbereich'},
        {"bufa": '9205', "name": 'Bad Kissingen'},
        {"bufa": '9206', "name": 'Bad Neustadt a.d.S.'},
        {"bufa": '9207', "name": 'Bamberg'},
        {"bufa": '9208', "name": 'Bayreuth'},
        {"bufa": '9105', "name": 'Berchtesgaden-Laufen'},
        {"bufa": '9116', "name": 'Bundeszentralamt für Steuern'},
        {"bufa": '9106', "name": 'Burghausen'},
        {"bufa": '9211', "name": 'Cham mit Außenstelle Bad Kötzting'},
        {"bufa": '9212', "name": 'Coburg'},
        {"bufa": '9107', "name": 'Dachau'},
        {"bufa": '9108', "name": 'Deggendorf'},
        {"bufa": '9109', "name": 'Dillingen'},
        {"bufa": '9110', "name": 'Dingolfing'},
        {"bufa": '9112', "name": 'Ebersberg'},
        {"bufa": '9113', "name": 'Eggenfelden'},
        {"bufa": '9171', "name": 'Eichstätt'},
        {"bufa": '9114', "name": 'Erding'},
        {"bufa": '9216', "name": 'Erlangen'},
        {"bufa": '9217', "name": 'Forchheim'},
        {"bufa": '9115', "name": 'Freising'},
        {"bufa": '9117', "name": 'Fürstenfeldbruck'},
        {"bufa": '9218', "name": 'Fürth'},
        {"bufa": '9119', "name": 'Garmisch-Partenkirchen'},
        {"bufa": '9157', "name": 'Grafenau'},
        {"bufa": '9220', "name": 'Gunzenhausen'},
        {"bufa": '9121', "name": 'Günzburg'},
        {"bufa": '9221', "name": 'Hersbruck'},
        {"bufa": '9222', "name": 'Hilpoltstein'},
        {"bufa": '9223', "name": 'Hof mit Außenstellen'},
        {"bufa": '9124', "name": 'Ingolstadt'},
        {"bufa": '9125', "name": 'Kaufbeuren m. ASt Füssen'},
        {"bufa": '9126', "name": 'Kelheim'},
        {"bufa": '9123', "name": 'Kempten-Immenstadt'},
        {"bufa": '9127', "name": 'Kempten-Immenstadt'},
        {"bufa": '9227', "name": 'Kitzingen'},
        {"bufa": '9228', "name": 'Kronach'},
        {"bufa": '9229', "name": 'Kulmbach'},
        {"bufa": '9131', "name": 'Landsberg am Lech'},
        {"bufa": '9132', "name": 'Landshut'},
        {"bufa": '9230', "name": 'Lichtenfels'},
        {"bufa": '9134', "name": 'Lindau'},
        {"bufa": '9231', "name": 'Lohr a. Main mit Außenstellen'},
        {"bufa": '9232', "name": 'Lohr a. Main mit Außenstellen - Grunderwerbsteuer'},
        {"bufa": '9138', "name": 'Memmingen-Mindelheim'},
        {"bufa": '9140', "name": 'Memmingen-Mindelheim'},
        {"bufa": '9139', "name": 'Miesbach'},
        {"bufa": '9141', "name": 'Mühldorf'},
        {"bufa": '9188', "name": 'München Betriebsprüfung'},
        {"bufa": '9142', "name": 'München Bewertung des Grundbesitzes'},
        {"bufa": '9149', "name": 'München Erhebung'},
        {"bufa": '9189', "name": 'München Erhebung'},
        {"bufa": '9144', "name": 'München Gewinneinkünfte'},
        {"bufa": '9145', "name": 'München Gewinneinkünfte'},
        {"bufa": '9146', "name": 'München Gewinneinkünfte'},
        {"bufa": '9147', "name": 'München Gewinneinkünfte'},
        {"bufa": '9148', "name": 'München Gewinneinkünfte'},
        {"bufa": '9187', "name": 'München Körperschaften'},
        {"bufa": '9143', "name": 'München Körperschaften/PersonenGesellschaften'},
        {"bufa": '9181', "name": 'München Überschusseinkünfte'},
        {"bufa": '9183', "name": 'München Überschusseinkünfte'},
        {"bufa": '9184', "name": 'München Überschusseinkünfte'},
        {"bufa": '9185', "name": 'München Überschusseinkünfte'},
        {"bufa": '9182', "name": 'München Überschusseinkünfte u. Beschränkt Steuerpfl.'},
        {"bufa": '9151', "name": 'Neu-Ulm'},
        {"bufa": '9235', "name": 'Neumarkt i.d.Opf.'},
        {"bufa": '9111', "name": 'Nördlingen mit ASt Donauwörth'},
        {"bufa": '9152', "name": 'Nördlingen mit ASt Donauwörth'},
        {"bufa": '9238', "name": 'Nürnberg-Nord'},
        {"bufa": '9240', "name": 'Nürnberg-Süd'},
        {"bufa": '9241', "name": 'Nürnberg-Zentral'},
        {"bufa": '9202', "name": 'Obernburg am Main mit Außenstelle Amorbach'},
        {"bufa": '9153', "name": 'Passau mit Außenstellen'},
        {"bufa": '9154', "name": 'Pfaffenhofen'},
        {"bufa": '9244', "name": 'Regensburg'},
        {"bufa": '9156', "name": 'Rosenheim m. ASt Wasserburg'},
        {"bufa": '9159', "name": 'Schrobenhausen m. ASt Neuburg'},
        {"bufa": '9247', "name": 'Schwabach'},
        {"bufa": '9248', "name": 'Schwandorf mit Außenstelle Neunburg v. W.'},
        {"bufa": '9249', "name": 'Schweinfurt'},
        {"bufa": '9161', "name": 'Starnberg'},
        {"bufa": '9162', "name": 'Straubing'},
        {"bufa": '9163', "name": 'Traunstein'},
        {"bufa": '9252', "name": 'Uffenheim'},
        {"bufa": '9254', "name": 'Waldsassen'},
        {"bufa": '9255', "name": 'Weiden i.d.Opf.'},
        {"bufa": '9168', "name": 'Weilheim-Schongau'},
        {"bufa": '9104', "name": 'Wolfratshausen - Bad Tölz'},
        {"bufa": '9169', "name": 'Wolfratshausen - Bad Tölz'},
        {"bufa": '9258', "name": 'Wunsiedel mit Außenstelle Selb'},
        {"bufa": '9257', "name": 'Würzburg mit Außenstelle Ochsenfurt'},
        {"bufa": '9259', "name": 'Zeil am Main mit Außenstelle Ebern'},
        {"bufa": '9170', "name": 'Zwiesel m. ASt Viechtach'},
    ],
    'Berlin': [
        {"bufa": '1115', "name": 'Berlin International'},
        {"bufa": '1113', "name": 'Charlottenburg'},
        {"bufa": '1114', "name": 'Friedrichshain-Kreuzberg'},
        {"bufa": '1138', "name": 'für Fahndung und Strafsachen Berlin'},
        {"bufa": '1127', "name": 'für Körperschaften I'},
        {"bufa": '1137', "name": 'für Körperschaften II'},
        {"bufa": '1129', "name": 'für Körperschaften III'},
        {"bufa": '1130', "name": 'für Körperschaften IV'},
        {"bufa": '1132', "name": 'Lichtenberg'},
        {"bufa": '1133', "name": 'Marzahn-Hellersdorf'},
        {"bufa": '1134', "name": 'Mitte/Tiergarten'},
        {"bufa": '1116', "name": 'Neukölln'},
        {"bufa": '1135', "name": 'Pankow/Weißensee'},
        {"bufa": '1131', "name": 'Prenzlauer Berg'},
        {"bufa": '1117', "name": 'Reinickendorf'},
        {"bufa": '1118', "name": 'Schöneberg'},
        {"bufa": '1119', "name": 'Spandau'},
        {"bufa": '1120', "name": 'Steglitz'},
        {"bufa": '1191', "name": 'Technisches Finanzamt Berlin'},
        {"bufa": '1121', "name": 'Tempelhof'},
        {"bufa": '1136', "name": 'Treptow-Köpenick'},
        {"bufa": '1123', "name": 'Wedding'},
        {"bufa": '1124', "name": 'Wilmersdorf'},
        {"bufa": '1125', "name": 'Zehlendorf'},
    ],
    'Brandenburg': [
        {"bufa": '3062', "name": 'Angermünde'},
        {"bufa": '3048', "name": 'Brandenburg'},
        {"bufa": '3057', "name": 'Calau'},
        {"bufa": '3056', "name": 'Cottbus'},
        {"bufa": '3065', "name": 'Eberswalde'},
        {"bufa": '3061', "name": 'Frankfurt (Oder)'},
        {"bufa": '3052', "name": 'Kyritz'},
        {"bufa": '3049', "name": 'Königs Wusterhausen'},
        {"bufa": '3050', "name": 'Luckenwalde'},
        {"bufa": '3051', "name": 'Nauen'},
        {"bufa": '3053', "name": 'Oranienburg'},
        {"bufa": '3046', "name": 'Potsdam'},
        {"bufa": '3064', "name": 'Strausberg'},
    ],
    'Bremen': [
        {"bufa": '2460', "name": 'Bremen'},
        {"bufa": '2478', "name": 'Bremen für Außenprüfung'},
        {"bufa": '2475', "name": 'Bremerhaven'},
        {"bufa": '2477', "name": 'Bremerhaven Bewertung'},
        {"bufa": '2457', "name": 'Bremerhaven Bewertung Bremen'},
        {"bufa": '2471', "name": 'Landeshauptkasse Bremen'},
    ],
    'Hamburg': [
        {"bufa": '2227', "name": 'Hamburg für Großunternehmen in Hamburg'},
        {"bufa": '2228', "name": 'Hamburg für Prüfungsd. und Strafsachen'},
        {"bufa": '2201', "name": 'Hamburg für Steuererhebung in Hamburg'},
        {"bufa": '2210', "name": 'Hamburg für Verkehrst. und Grundbesitz'},
        {"bufa": '2216', "name": 'Hamburg für Verkehrst. und Grundbesitz'},
        {"bufa": '2220', "name": 'Hamburg für Verkehrst. und Grundbesitz'},
        {"bufa": '2230', "name": 'Hamburg für Verkehrst. und Grundbesitz'},
        {"bufa": '2235', "name": 'Hamburg für Verkehrst. und Grundbesitz'},
        {"bufa": '2241', "name": 'Hamburg-Altona'},
        {"bufa": '2242', "name": 'Hamburg-Am Tierpark'},
        {"bufa": '2243', "name": 'Hamburg-Barmbek-Uhlenhorst'},
        {"bufa": '2245', "name": 'Hamburg-Eimsbüttel'},
        {"bufa": '2246', "name": 'Hamburg-Hansa'},
        {"bufa": '2247', "name": 'Hamburg-Harburg'},
        {"bufa": '2248', "name": 'Hamburg-Mitte'},
        {"bufa": '2217', "name": 'Hamburg-Nord'},
        {"bufa": '2249', "name": 'Hamburg-Nord'},
        {"bufa": '2250', "name": 'Hamburg-Oberalster'},
        {"bufa": '2244', "name": 'Hamburg-Ost'},
        {"bufa": '2251', "name": 'Hamburg-Ost'},
    ],
    'Hessen': [
        {"bufa": '2601', "name": 'Alsfeld-Lauterbach Verwaltungsstelle Alsfeld'},
        {"bufa": '2629', "name": 'Alsfeld-Lauterbach Verwaltungsstelle Lauterbach'},
        {"bufa": '2603', "name": 'Bad Homburg vor der Höhe'},
        {"bufa": '2605', "name": 'Bensheim'},
        {"bufa": '2617', "name": 'Bensheim Außenstelle Fürth'},
        {"bufa": '2607', "name": 'Darmstadt'},
        {"bufa": '2608', "name": 'Dieburg'},
        {"bufa": '2609', "name": 'Dillenburg'},
        {"bufa": '2610', "name": 'Eschwege-Witzenhausen Verwaltungsstelle Eschwege'},
        {"bufa": '2641', "name": 'Eschwege-Witzenhausen Verwaltungsstelle Witzenhausen'},
        {"bufa": '2612', "name": 'Frankfurt am Main'},
        {"bufa": '2613', "name": 'Frankfurt am Main'},
        {"bufa": '2614', "name": 'Frankfurt am Main'},
        {"bufa": '2615', "name": 'Frankfurt am Main'},
        {"bufa": '2645', "name": 'Frankfurt am Main'},
        {"bufa": '2647', "name": 'Frankfurt am Main'},
        {"bufa": '2616', "name": 'Friedberg (Hessen)'},
        {"bufa": '2618', "name": 'Fulda'},
        {"bufa": '2619', "name": 'Gelnhausen'},
        {"bufa": '2620', "name": 'Gießen'},
        {"bufa": '2621', "name": 'Groß-Gerau'},
        {"bufa": '2622', "name": 'Hanau'},
        {"bufa": '2602', "name": 'Hersfeld-Rotenburg Verwaltungsstelle Bad Hersfeld'},
        {"bufa": '2636', "name": 'Hersfeld-Rotenburg Verwaltungsstelle Rotenburg'},
        {"bufa": '2646', "name": 'Hofheim am Taunus'},
        {"bufa": '2623', "name": 'Kassel'},
        {"bufa": '2625', "name": 'Kassel'},
        {"bufa": '2626', "name": 'Kassel'},
        {"bufa": '2611', "name": 'Korbach-Frankenberg Verwaltungsstelle Frankenberg'},
        {"bufa": '2627', "name": 'Korbach-Frankenberg Verwaltungsstelle Korbach'},
        {"bufa": '2628', "name": 'Langen'},
        {"bufa": '2630', "name": 'Limburg-Weilburg Verwaltungsstelle Limburg'},
        {"bufa": '2638', "name": 'Limburg-Weilburg Verwaltungsstelle Weilburg'},
        {"bufa": '2606', "name": 'Marburg-Biedenkopf Verwaltungsstelle Biedenkopf'},
        {"bufa": '2631', "name": 'Marburg-Biedenkopf Verwaltungsstelle Marburg'},
        {"bufa": '2633', "name": 'Michelstadt'},
        {"bufa": '2634', "name": 'Nidda'},
        {"bufa": '2635', "name": 'Offenbach am Main'},
        {"bufa": '2644', "name": 'Offenbach am Main'},
        {"bufa": '2604', "name": 'Rheingau-Taunus Verwaltungsstelle Bad Schwalbach'},
        {"bufa": '2637', "name": 'Rheingau-Taunus Verwaltungsstelle Rüdesheim'},
        {"bufa": '2624', "name": 'Schwalm-Eder Verwaltungsstelle Fritzlar'},
        {"bufa": '2632', "name": 'Schwalm-Eder Verwaltungsstelle Melsungen'},
        {"bufa": '2642', "name": 'Schwalm-Eder Verwaltungsstelle Schwalmstadt'},
        {"bufa": '2639', "name": 'Wetzlar'},
        {"bufa": '2640', "name": 'Wiesbaden'},
        {"bufa": '2643', "name": 'Wiesbaden'},
    ],
    'Mecklenburg-Vorpommern': [
        {"bufa": '4084', "name": 'Greifswald'},
        {"bufa": '4086', "name": 'Güstrow'},
        {"bufa": '4087', "name": 'Hagenow'},
        {"bufa": '4072', "name": 'Neubrandenburg'},
        {"bufa": '4069', "name": 'Neubrandenburg - RAB'},
        {"bufa": '4070', "name": 'Neubrandenburg - RIA (Rentenempfänger im Ausland)'},
        {"bufa": '4081', "name": 'Ribnitz-Damgarten'},
        {"bufa": '4079', "name": 'Rostock'},
        {"bufa": '4090', "name": 'Schwerin'},
        {"bufa": '4082', "name": 'Stralsund'},
        {"bufa": '4075', "name": 'Waren'},
        {"bufa": '4080', "name": 'Wismar'},
    ],
    'Niedersachsen': [
        {"bufa": '2354', "name": 'Aurich-Wittmund'},
        {"bufa": '2355', "name": 'Bad Bentheim'},
        {"bufa": '2380', "name": 'Braunschweig für Großbetriebsprüfung'},
        {"bufa": '2313', "name": 'Braunschweig-Helmstedt'},
        {"bufa": '2314', "name": 'Braunschweig-Wilhelmstr.'},
        {"bufa": '2315', "name": 'Buchholz in der Nordheide'},
        {"bufa": '2316', "name": 'Burgdorf'},
        {"bufa": '2317', "name": 'Celle'},
        {"bufa": '2356', "name": 'Cloppenburg'},
        {"bufa": '2318', "name": 'Cuxhaven'},
        {"bufa": '2357', "name": 'Delmenhorst'},
        {"bufa": '2358', "name": 'Emden-Norden'},
        {"bufa": '2390', "name": 'für Fahndung und Strafsachen Braunschweig'},
        {"bufa": '2319', "name": 'Gifhorn'},
        {"bufa": '2321', "name": 'Goslar-Bad Gandersheim'},
        {"bufa": '2320', "name": 'Göttingen'},
        {"bufa": '2381', "name": 'Göttingen für Großbetriebsprüfung'},
        {"bufa": '2322', "name": 'Hameln-Holzminden'},
        {"bufa": '2391', "name": 'Hannover für Fahndung und Strafsachen'},
        {"bufa": '2382', "name": 'Hannover für Großbetriebsprüfung'},
        {"bufa": '2323', "name": 'Hannover-Land I'},
        {"bufa": '2327', "name": 'Hannover-Land II'},
        {"bufa": '2324', "name": 'Hannover-Mitte'},
        {"bufa": '2325', "name": 'Hannover-Nord'},
        {"bufa": '2326', "name": 'Hannover-Süd'},
        {"bufa": '2328', "name": 'Helmstedt'},
        {"bufa": '2330', "name": 'Hildesheim-Alfeld'},
        {"bufa": '2331', "name": 'Holzminden'},
        {"bufa": '2360', "name": 'Leer (Ostfriesland)'},
        {"bufa": '2361', "name": 'Lingen (Ems)'},
        {"bufa": '2333', "name": 'Lüneburg'},
        {"bufa": '2392', "name": 'Lüneburg für Fahndung und Strafsachen'},
        {"bufa": '2334', "name": 'Nienburg/Weser'},
        {"bufa": '2363', "name": 'Nordenham'},
        {"bufa": '2335', "name": 'Northeim-Herzberg am Harz'},
        {"bufa": '2364', "name": 'Oldenburg (Oldenburg)'},
        {"bufa": '2393', "name": 'Oldenburg für Fahndung und Strafsachen'},
        {"bufa": '2385', "name": 'Oldenburg für Großbetriebsprüfung'},
        {"bufa": '2386', "name": 'Osnabrück für Großbetriebsprüfung'},
        {"bufa": '2365', "name": 'Osnabrück-Land'},
        {"bufa": '2366', "name": 'Osnabrück-Stadt'},
        {"bufa": '2336', "name": 'Osterholz-Scharmbeck'},
        {"bufa": '2353', "name": 'Papenburg'},
        {"bufa": '2338', "name": 'Peine'},
        {"bufa": '2367', "name": 'Quakenbrück'},
        {"bufa": '2340', "name": 'Rotenburg (Wümme)'},
        {"bufa": '2341', "name": 'Soltau'},
        {"bufa": '2343', "name": 'Stade'},
        {"bufa": '2384', "name": 'Stade für Großbetriebsprüfung'},
        {"bufa": '2344', "name": 'Stadthagen'},
        {"bufa": '2345', "name": 'Sulingen'},
        {"bufa": '2346', "name": 'Syke'},
        {"bufa": '2347', "name": 'Uelzen-Lüchow'},
        {"bufa": '2368', "name": 'Vechta'},
        {"bufa": '2348', "name": 'Verden (Aller)'},
        {"bufa": '2349', "name": 'Wesermünde'},
        {"bufa": '2369', "name": 'Westerstede'},
        {"bufa": '2370', "name": 'Wilhelmshaven'},
        {"bufa": '2350', "name": 'Winsen (Luhe)'},
        {"bufa": '2351', "name": 'Wolfenbüttel'},
        {"bufa": '2352', "name": 'Zeven'},
    ],
    'Nordrhein-Westfalen': [
        {"bufa": '5271', "name": 'Aachen für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5202', "name": 'Aachen-Kreis'},
        {"bufa": '5201', "name": 'Aachen-Stadt'},
        {"bufa": '5301', "name": 'Ahaus'},
        {"bufa": '5302', "name": 'Altena'},
        {"bufa": '5303', "name": 'Arnsberg'},
        {"bufa": '5304', "name": 'Beckum'},
        {"bufa": '5203', "name": 'Bergheim'},
        {"bufa": '5204', "name": 'Bergisch Gladbach'},
        {"bufa": '5174', "name": 'Bergisches Land für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5371', "name": 'Bielefeld für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5349', "name": 'Bielefeld-Außenstadt'},
        {"bufa": '5305', "name": 'Bielefeld-Innenstadt'},
        {"bufa": '5306', "name": 'Bochum-Mitte'},
        {"bufa": '5350', "name": 'Bochum-Süd'},
        {"bufa": '5272', "name": 'Bonn für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5206', "name": 'Bonn-Außenstadt'},
        {"bufa": '5205', "name": 'Bonn-Innenstadt'},
        {"bufa": '5307', "name": 'Borken'},
        {"bufa": '5308', "name": 'Bottrop'},
        {"bufa": '5309', "name": 'Brilon'},
        {"bufa": '5224', "name": 'Brühl'},
        {"bufa": '5310', "name": 'Bünde'},
        {"bufa": '5312', "name": 'Coesfeld'},
        {"bufa": '5313', "name": 'Detmold'},
        {"bufa": '5373', "name": 'Detmold für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5101', "name": 'Dinslaken'},
        {"bufa": '5374', "name": 'Dortmund für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5315', "name": 'Dortmund-Hörde'},
        {"bufa": '5317', "name": 'Dortmund-Ost'},
        {"bufa": '5316', "name": 'Dortmund-Unna'},
        {"bufa": '5314', "name": 'Dortmund-West'},
        {"bufa": '5107', "name": 'Duisburg-Hamborn'},
        {"bufa": '5109', "name": 'Duisburg-Süd'},
        {"bufa": '5134', "name": 'Duisburg-West'},
        {"bufa": '5207', "name": 'Düren'},
        {"bufa": '5170', "name": 'Düsseldorf I für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5171', "name": 'Düsseldorf II für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5103', "name": 'Düsseldorf-Altstadt'},
        {"bufa": '5147', "name": 'Düsseldorf-Mettmann'},
        {"bufa": '5133', "name": 'Düsseldorf-Mitte'},
        {"bufa": '5105', "name": 'Düsseldorf-Nord'},
        {"bufa": '5106', "name": 'Düsseldorf-Süd'},
        {"bufa": '5208', "name": 'Erkelenz'},
        {"bufa": '5172', "name": 'Essen für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5111', "name": 'Essen-NordOst'},
        {"bufa": '5112', "name": 'Essen-Süd'},
        {"bufa": '5209', "name": 'Euskirchen'},
        {"bufa": '5210', "name": 'Geilenkirchen'},
        {"bufa": '5113', "name": 'Geldern'},
        {"bufa": '5319', "name": 'Gelsenkirchen'},
        {"bufa": '5114', "name": 'Grevenbroich'},
        {"bufa": '5212', "name": 'Gummersbach'},
        {"bufa": '5351', "name": 'Gütersloh'},
        {"bufa": '5321', "name": 'Hagen'},
        {"bufa": '5375', "name": 'Hagen für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5322', "name": 'Hamm'},
        {"bufa": '5323', "name": 'Hattingen'},
        {"bufa": '5324', "name": 'Herford'},
        {"bufa": '5325', "name": 'Herne'},
        {"bufa": '5372', "name": 'Herne für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5135', "name": 'Hilden'},
        {"bufa": '5326', "name": 'Höxter'},
        {"bufa": '5327', "name": 'Ibbenbüren'},
        {"bufa": '5328', "name": 'Iserlohn'},
        {"bufa": '5213', "name": 'Jülich'},
        {"bufa": '5119', "name": 'Kamp-Lintfort'},
        {"bufa": '5115', "name": 'Kempen'},
        {"bufa": '5116', "name": 'Kleve'},
        {"bufa": '5117', "name": 'Krefeld'},
        {"bufa": '5173', "name": 'Krefeld für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5270', "name": 'Köln für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5214', "name": 'Köln-Altstadt'},
        {"bufa": '5215', "name": 'Köln-Mitte'},
        {"bufa": '5217', "name": 'Köln-Nord'},
        {"bufa": '5218', "name": 'Köln-Ost'},
        {"bufa": '5216', "name": 'Köln-Porz'},
        {"bufa": '5219', "name": 'Köln-Süd'},
        {"bufa": '5223', "name": 'Köln-West'},
        {"bufa": '5380', "name": 'Landesamt zur Bekämpfung der Finanzkriminalität'},
        {"bufa": '5329', "name": 'Lemgo'},
        {"bufa": '5230', "name": 'Leverkusen'},
        {"bufa": '5330', "name": 'Lippstadt'},
        {"bufa": '5331', "name": 'Lübbecke'},
        {"bufa": '5332', "name": 'Lüdenscheid'},
        {"bufa": '5333', "name": 'Lüdinghausen'},
        {"bufa": '5359', "name": 'Marl'},
        {"bufa": '5334', "name": 'Meschede'},
        {"bufa": '5335', "name": 'Minden'},
        {"bufa": '5121', "name": 'Mönchengladbach'},
        {"bufa": '5176', "name": 'Mönchengladbach für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5120', "name": 'Mülheim an der Ruhr'},
        {"bufa": '5376', "name": 'Münster für Groß- und Konzernbetriebsprüfung'},
        {"bufa": '5336', "name": 'Münster-Außenstadt'},
        {"bufa": '5337', "name": 'Münster-Innenstadt'},
        {"bufa": '5122', "name": 'Neuss'},
        {"bufa": '5123', "name": 'Oberhausen-Nord'},
        {"bufa": '5124', "name": 'Oberhausen-Süd'},
        {"bufa": '5338', "name": 'Olpe'},
        {"bufa": '5339', "name": 'Paderborn'},
        {"bufa": '5340', "name": 'Recklinghausen'},
        {"bufa": '5126', "name": 'Remscheid'},
        {"bufa": '5222', "name": 'Sankt Augustin'},
        {"bufa": '5211', "name": 'Schleiden'},
        {"bufa": '5341', "name": 'Schwelm'},
        {"bufa": '5220', "name": 'Siegburg'},
        {"bufa": '5342', "name": 'Siegen'},
        {"bufa": '5343', "name": 'Soest'},
        {"bufa": '5128', "name": 'Solingen'},
        {"bufa": '5311', "name": 'Steinfurt'},
        {"bufa": '5139', "name": 'Velbert'},
        {"bufa": '5102', "name": 'Viersen'},
        {"bufa": '5345', "name": 'Warburg'},
        {"bufa": '5346', "name": 'Warendorf'},
        {"bufa": '5130', "name": 'Wesel'},
        {"bufa": '5347', "name": 'Wiedenbrück'},
        {"bufa": '5221', "name": 'Wipperfürth'},
        {"bufa": '5348', "name": 'Witten'},
        {"bufa": '5131', "name": 'Wuppertal-Barmen'},
        {"bufa": '5132', "name": 'Wuppertal-Elberfeld'},
    ],
    'Rheinland-Pfalz': [
        {"bufa": '2702', "name": 'Altenkirchen-Hachenburg'},
        {"bufa": '2706', "name": 'Bad Kreuznach'},
        {"bufa": '2701', "name": 'Bad Neuenahr-Ahrweiler'},
        {"bufa": '2708', "name": 'Bingen-Alzey'},
        {"bufa": '2710', "name": 'Bitburg-Prüm'},
        {"bufa": '2709', "name": 'Idar-Oberstein'},
        {"bufa": '2713', "name": 'Idar-Oberstein - Landesfinanzkasse'},
        {"bufa": '2719', "name": 'Kaiserslautern'},
        {"bufa": '2722', "name": 'Koblenz'},
        {"bufa": '2723', "name": 'Kusel-Landstuhl'},
        {"bufa": '2734', "name": 'Kusel-Landstuhl für Erb/Schenk.St. Saarland'},
        {"bufa": '2724', "name": 'Landau'},
        {"bufa": '2727', "name": 'Ludwigshafen'},
        {"bufa": '2726', "name": 'Mainz'},
        {"bufa": '2729', "name": 'Mayen'},
        {"bufa": '2730', "name": 'Montabaur-Diez'},
        {"bufa": '2731', "name": 'Neustadt'},
        {"bufa": '2732', "name": 'Neuwied'},
        {"bufa": '2735', "name": 'Pirmasens'},
        {"bufa": '2740', "name": 'Simmern-Zell'},
        {"bufa": '2741', "name": 'Speyer-Germersheim'},
        {"bufa": '2742', "name": 'Trier'},
        {"bufa": '2743', "name": 'Wittlich'},
        {"bufa": '2744', "name": 'Worms-Kirchheimbolanden'},
    ],
    'Saarland': [
        {"bufa": '1075', "name": 'Homburg'},
        {"bufa": '1085', "name": 'Homburg - Außenst. St. Ingbert'},
        {"bufa": '1020', "name": 'Merzig'},
        {"bufa": '1030', "name": 'Neunkirchen'},
        {"bufa": '1040', "name": 'Saarbrücken I'},
        {"bufa": '1055', "name": 'Saarbrücken II'},
        {"bufa": '1010', "name": 'Saarlouis'},
        {"bufa": '1060', "name": 'St. Wendel'},
    ],
    'Sachsen': [
        {"bufa": '3217', "name": 'Annaberg'},
        {"bufa": '3204', "name": 'Bautzen'},
        {"bufa": '3215', "name": 'Chemnitz-Mitte'},
        {"bufa": '3214', "name": 'Chemnitz-Süd'},
        {"bufa": '3202', "name": 'Dresden-Nord'},
        {"bufa": '3203', "name": 'Dresden-Süd'},
        {"bufa": '3236', "name": 'Döbeln'},
        {"bufa": '3237', "name": 'Eilenburg'},
        {"bufa": '3220', "name": 'Freiberg'},
        {"bufa": '3238', "name": 'Grimma'},
        {"bufa": '3207', "name": 'Görlitz'},
        {"bufa": '3213', "name": 'Hoyerswerda'},
        {"bufa": '3232', "name": 'Leipzig I'},
        {"bufa": '3231', "name": 'Leipzig II'},
        {"bufa": '3208', "name": 'Löbau'},
        {"bufa": '3209', "name": 'Meißen'},
        {"bufa": '3222', "name": 'Mittweida'},
        {"bufa": '3239', "name": 'Oschatz'},
        {"bufa": '3210', "name": 'Pirna'},
        {"bufa": '3223', "name": 'Plauen'},
        {"bufa": '3218', "name": 'Schwarzenberg'},
        {"bufa": '3224', "name": 'Stollberg'},
        {"bufa": '3228', "name": 'Zschopau'},
        {"bufa": '3227', "name": 'Zwickau'},
    ],
    'Sachsen-Anhalt': [
        {"bufa": '3116', "name": 'Bitterfeld-Wolfen'},
        {"bufa": '3114', "name": 'Dessau-Roßlau'},
        {"bufa": '3118', "name": 'Eisleben'},
        {"bufa": '3103', "name": 'Genthin'},
        {"bufa": '3105', "name": 'Haldensleben'},
        {"bufa": '3110', "name": 'Halle (Saale)'},
        {"bufa": '3102', "name": 'Magdeburg'},
        {"bufa": '3112', "name": 'Merseburg'},
        {"bufa": '3119', "name": 'Naumburg'},
        {"bufa": '3117', "name": 'Quedlinburg'},
        {"bufa": '3106', "name": 'Salzwedel'},
        {"bufa": '3107', "name": 'Staßfurt'},
        {"bufa": '3108', "name": 'Stendal'},
        {"bufa": '3115', "name": 'Wittenberg'},
    ],
    'Schleswig-Holstein': [
        {"bufa": '2111', "name": 'Bad Segeberg'},
        {"bufa": '2171', "name": 'Bad Segeberg Bewertung für Grundsteuer 71'},
        {"bufa": '2116', "name": 'Dithmarschen'},
        {"bufa": '2176', "name": 'Dithmarschen Bewertung für Grundsteuer 76'},
        {"bufa": '2183', "name": 'Dithmarschen Bewertung für Grundsteuer 83'},
        {"bufa": '2129', "name": 'Eckernförde-Schleswig'},
        {"bufa": '2172', "name": 'Eckernförde-Schleswig Bewertung für Grundsteuer 72'},
        {"bufa": '2189', "name": 'Eckernförde-Schleswig Bewertung für Grundsteuer 89'},
        {"bufa": '2113', "name": 'Elmshorn'},
        {"bufa": '2173', "name": 'Elmshorn Bewertung für Grundsteuer 73'},
        {"bufa": '2115', "name": 'Flensburg'},
        {"bufa": '2175', "name": 'Flensburg Bewertung für Grundsteuer 75'},
        {"bufa": '2118', "name": 'Itzehoe'},
        {"bufa": '2178', "name": 'Itzehoe Bewertung für Grundsteuer 78'},
        {"bufa": '2120', "name": 'Kiel'},
        {"bufa": '2179', "name": 'Kiel Bewertung für Grundsteuer 79'},
        {"bufa": '2180', "name": 'Kiel Bewertung für Grundsteuer 80'},
        {"bufa": '2122', "name": 'Lübeck'},
        {"bufa": '2182', "name": 'Lübeck Bewertung für Grundsteuer 82'},
        {"bufa": '2124', "name": 'Neumünster'},
        {"bufa": '2184', "name": 'Neumünster Bewertung für Grundsteuer 84'},
        {"bufa": '2117', "name": 'Nordfriesland'},
        {"bufa": '2177', "name": 'Nordfriesland Bewertung für Grundsteuer 77'},
        {"bufa": '2181', "name": 'Nordfriesland Bewertung für Grundsteuer 81'},
        {"bufa": '2125', "name": 'Ostholstein'},
        {"bufa": '2185', "name": 'Ostholstein Bewertung für Grundsteuer 85'},
        {"bufa": '2131', "name": 'Pinneberg'},
        {"bufa": '2191', "name": 'Pinneberg Bewertung für Grundsteuer 91'},
        {"bufa": '2126', "name": 'Plön'},
        {"bufa": '2186', "name": 'Plön Bewertung für Grundsteuer 86'},
        {"bufa": '2127', "name": 'Ratzeburg'},
        {"bufa": '2187', "name": 'Ratzeburg Bewertung für Grundsteuer 87'},
        {"bufa": '2128', "name": 'Rendsburg'},
        {"bufa": '2188', "name": 'Rendsburg Bewertung für Grundsteuer 88'},
        {"bufa": '2130', "name": 'Stormarn'},
        {"bufa": '2190', "name": 'Stormarn Bewertung für Grundsteuer 90'},
        {"bufa": '2137', "name": 'Zentrale Prüfungsdienste'},
    ],
    'Thüringen': [
        {"bufa": '4166', "name": 'Altenburg'},
        {"bufa": '4155', "name": 'Eisenach'},
        {"bufa": '4151', "name": 'Erfurt'},
        {"bufa": '4161', "name": 'Gera'},
        {"bufa": '4156', "name": 'Gotha'},
        {"bufa": '4154', "name": 'Ilmenau'},
        {"bufa": '4162', "name": 'Jena'},
        {"bufa": '4157', "name": 'Mühlhausen'},
        {"bufa": '4165', "name": 'Pößneck'},
        {"bufa": '4159', "name": 'Sondershausen'},
        {"bufa": '4170', "name": 'Südthüringen'},
        {"bufa": '4171', "name": 'Südthüringen'},
    ],
}

